# fly.toml app configuration file generated for aftermath-bot on 2024-02-01T13:25:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aftermath-bot'
primary_region = 'lhr'

[build]

[env]
CORE_SERVICE_URL = 'http://aftermath-core.internal:9090/v1'
PRIMARY_GUILD_ID = '1195871408392257668'
FRONTEND_URL = 'https://amth.one'
LOG_LEVEL = 'info'
PORT = '9090'

[processes]
app = 'run --allow-net --allow-env --allow-read ./main.ts'

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory_mb = 512
